import{a as u,S as p,i as d}from"./assets/vendor-d911e7d7.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const f="42508369-6cc99fb978405cb8598a23b23",m="https://pixabay.com/api/",h="photo",y="horizontal",g=!0;async function E(s){const r=encodeURIComponent(s),o=`${m}?key=${f}&q=${r}&image_type=${h}&orientation=${y}&safesearch=${g}`;try{return(await u.get(o)).data}catch(n){throw console.error("Error fetching images:",n),new Error("Error while fetching images from Pixabay")}}function L(s,r){r.innerHTML="";const o=s.map(e=>` <div class="card">
         <a href="${e.webformatURL}"><img class="card-image" src="${e.webformatURL}" alt="${e.tags}" />
         <div class="card-info">
           <p>Likes: <span>${e.likes}</span></p>
           <p>Views: <span>${e.views}</span></p>
           <p>Comments: <span>${e.comments}</span></p>
           <p>Downloads:<span>${e.downloads}</span></p>
         </div></a>
       </div> `).join("");r.innerHTML=o,new p(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function a(s){d.error({title:"Error",message:s,position:"topRight"})}const b=document.querySelector(".form"),c=document.querySelector(".search-input"),$=document.querySelector(".gallery"),l=document.querySelector(".loader");b.addEventListener("submit",function(s){s.preventDefault();const r=c.value.trim();if(r===""){a("Please fill imput");return}l.classList.remove("is-hidden"),E(r).then(o=>{if(o.hits.length===0){a("Sorry, there are no images matching your search query. Please try again!");return}L(o.hits,$),c.value=""}).catch(o=>{console.error("Error during search:",o),a("Error")}).finally(()=>{l.classList.add("is-hidden")})});
//# sourceMappingURL=commonHelpers.js.map
