import{S as l,i as u}from"./assets/vendor-5b791d57.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const p="42508369-6cc99fb978405cb8598a23b23",f="https://pixabay.com/api/",d="photo",m="horizontal",h=!0;function y(n){const r=encodeURIComponent(n),o=`${f}?key=${p}&q=${r}&image_type=${d}&orientation=${m}&safesearch=${h}`;return fetch(o).then(s=>{if(!s.ok)throw new Error("Image error");return s.json()}).catch(s=>{throw new Error("Error while fetching images from pixabay",s)})}function g(n,r){r.innerHTML="";const o=n.map(e=>` <div class="card">
         <a href="${e.webformatURL}"><img class="card-image" src="${e.webformatURL}" alt="${e.tags}" />
         <div class="card-info">
           <p>Likes: <span>${e.likes}</span></p>
           <p>Views: <span>${e.views}</span></p>
           <p>Comments: <span>${e.comments}</span></p>
           <p>Downloads:<span>${e.downloads}</span></p>
         </div></a>
       </div> `).join("");r.innerHTML=o,new l(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function c(n){u.error({title:"Error",message:n,position:"topRight"})}const E=document.querySelector("#search-form"),a=document.querySelector("#search-input"),b=document.querySelector(".gallery");E.addEventListener("submit",function(n){n.preventDefault();const r=a.value.trim();if(r===""){c("Please fill imput");return}y(r).then(o=>{if(o.hits.length===0){c("Sorry, there are no images matching your search query. Please try again!");return}g(o.hits,b),a.value=""}).catch(o=>{console.error("Error during search:",o),c("Error")})});
//# sourceMappingURL=commonHelpers.js.map
